# Site settings
name: Jamie Sherriff
description: "Welcome to my humble abode"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  jamie-sherriff
linkedin_username: jamie-sherriff
stack_of_username: 2224316


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars3.githubusercontent.com/u/11515002?v=3"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
